colors:
  body: none
  date: YELLOW
  tags: BLUE
  title: GREEN
default_hour: 9
default_minute: 0
editor: 'vim'
encrypt: false
highlight: true
indent_character: '|'
journals:
  default: ~/journals/journal.txt
  work: ~/journals/work.txt
  emotions: ~/journals/emotions.txt
linewrap: 79
tagsymbols: '@#'
template: false
timeformat: '%Y-%m-%d %H:%M'
version: v2.4.3
